### ISSUE TITLE
Assignment 1 - Introduction to Cloud Computing

### ISSUE THREAD

**Issue by manishawsdevops** [manishawsdevops/aws-devops-learning#13]
**List down the services for the below on AWS**

    -   Compute Services
    -   Storage and Content Delivery
    -   Databases
    - Explore different Cloud Vendors in the market and list most popular vendors and compare their market hold.

**Explore AWS Documentation and understand what is EC2 and its various attributes.**
**Start Exploring on Github and Linux OS**
Submit the assignment in the form of PDF

**Comment by Prakash0630** [comment]
E:\AWS\HandleException Tasks\CloudIntroTask.pdf

**Comment by manishawsdevops** [comment]
@Prakash0630 - Please don't close any of issues - I will review and close the issues. Only commit the changes into the branch and raise a PR.
