### ISSUE TITLE
Assignment 05 - Building Scalable application with AWS EC2

### ISSUE THREAD

**Issue by manishawsdevops** [manishawsdevops/aws-devops-learning#22]
**Assignment Title:** Implementing High Availability and Scalability with AWS EC2, Elastic Load Balancer, and Auto Scaling Groups

**Assignment Description:**

In this assignment, you will gain hands-on experience with Amazon Web Services (AWS) by setting up a highly available and scalable web application infrastructure using EC2 instances, Elastic Load Balancer (ELB), and Auto Scaling Groups (ASG). You will create a simple web application and ensure that it can handle increased traffic by automatically scaling the resources.

**Tasks:**

1. Setup a scalable web application using EC2, Autoscaling Group and Load balancer with below properties.
2. ASG desired capacity is 3 and Min of 2 instances and maximum of 5 instances.
3. Use the Amazon Linux AMI.
4. Setup Apache web server.
5. Ensure you display the Ip-Address of the instance in the browser using the webserver.

Submit the assignment with relevant screenshots and code as necessary.

**Comment by Prakash0630** [comment]
Good Morning Manish,

I have got it. I have seen it. I will be submitting by Monday.

Regards,
Sai Prakash
________________________________
